version: "3"

services:

  web:
    container_name: rest_api_sqlite3
    build: ./
    ports:
     - "8000:8000"

#   Comment volumes def below to run immutable container
    volumes:
      - ".:/api_testing/"

    command: bash -c "python manage.py runserver 0:8000"
