version: "3"

services:
  web:
    build: ./
    ports:
     - "8000:8000"

#   Comment volumes def below to run independent container
    volumes:
      - ".:/api_testing/"

    command: bash -c "python manage.py runserver 0:8000"
